In [1]:
import tensorflow as tf
import keras
import numpy as np

In [2]:
for i in range(10):
    lst = list(range(i, i+5))
    print(lst)

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]
[6, 7, 8, 9, 10]
[7, 8, 9, 10, 11]
[8, 9, 10, 11, 12]
[9, 10, 11, 12, 13]


In [3]:
X = []
Y = []

for i in range(10):
    lst = list( range(i, i+5) )
    X.append( [ [ c/10 ]  for c in lst ] ) # 입력
    Y.append( (i+5)/10 )                # 출력
    
X = np.array(X)
Y = np.array(Y)

print( X.shape, Y.shape )
print( X[0], Y[0])

(10, 5, 1) (10,)
[[0. ]
 [0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5


In [4]:
for i in range(len(X)):
    print(X[i], Y[i])
print(X.shape, Y.shape)

[[0. ]
 [0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.2]
 [0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.3]
 [0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8
[[0.4]
 [0.5]
 [0.6]
 [0.7]
 [0.8]] 0.9
[[0.5]
 [0.6]
 [0.7]
 [0.8]
 [0.9]] 1.0
[[0.6]
 [0.7]
 [0.8]
 [0.9]
 [1. ]] 1.1
[[0.7]
 [0.8]
 [0.9]
 [1. ]
 [1.1]] 1.2
[[0.8]
 [0.9]
 [1. ]
 [1.1]
 [1.2]] 1.3
[[0.9]
 [1. ]
 [1.1]
 [1.2]
 [1.3]] 1.4
(10, 5, 1) (10,)


In [6]:
#return_sequences True 는 hidden state 값까지 보여준다 
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=10, return_sequences=False, input_shape=[5,1]),
    tf.keras.layers.Dense(1)
])

In [7]:
model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 10)                120       
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.fit(X, Y, epochs=50, verbose=1)


Epoch 1/50
1/1 [==============================] - 1s 1s/step - loss: 3.1656
Epoch 2/50
1/1 [==============================] - 0s 11ms/step - loss: 3.0678
Epoch 3/50
1/1 [==============================] - 0s 9ms/step - loss: 2.9712
Epoch 4/50
1/1 [==============================] - 0s 10ms/step - loss: 2.8757
Epoch 5/50
1/1 [==============================] - 0s 13ms/step - loss: 2.7815
Epoch 6/50
1/1 [==============================] - 0s 8ms/step - loss: 2.6885
Epoch 7/50
1/1 [==============================] - 0s 10ms/step - loss: 2.5968
Epoch 8/50
1/1 [==============================] - 0s 7ms/step - loss: 2.5064
Epoch 9/50
1/1 [==============================] - 0s 11ms/step - loss: 2.4174
Epoch 10/50
1/1 [==============================] - 0s 8ms/step - loss: 2.3298
Epoch 11/50
1/1 [==============================] - 0s 6ms/step - loss: 2.2437
Epoch 12/50
1/1 [==============================] - 0s 7ms/step - loss: 2.1589
Epoch 13/50
1/1 [==============================] - 0s 7ms/step - loss