In [ ]:
import numpy as np

user1 = np.array([2,2,1,2])
user2 = np.array([1,1,2,1])
user3 = np.array([2,2,1,0])

rMatrix = np.vstack((user1, user2, user3))

print(rMatrix.shape)
rMatrix

(3, 4)


array([[2, 2, 1, 2],
       [1, 1, 2, 1],
       [2, 2, 1, 0]])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosingSim = cosine_similarity(rMatrix)
print(cosingSim.shape)
cosingSim

(3, 3)


array([[1.        , 0.83862787, 0.83205029],
       [0.83862787, 1.        , 0.75592895],
       [0.83205029, 0.75592895, 1.        ]])

In [ ]:
rMatrix_t = np.transpose(rMatrix)
print(rMatrix.shape)
rMatrix_t

(3, 4)


array([[2, 1, 2],
       [2, 1, 2],
       [1, 2, 1],
       [2, 1, 0]])

In [ ]:
cosineSim_t = cosine_similarity(rMatrix_t)
cosineSim_t

array([[1.        , 1.        , 0.81649658, 0.74535599],
       [1.        , 1.        , 0.81649658, 0.74535599],
       [0.81649658, 0.81649658, 1.        , 0.73029674],
       [0.74535599, 0.74535599, 0.73029674, 1.        ]])

In [1]:
import pandas as pd

In [6]:
columns = ['user_id', 'item_id', 'rating', 'timestamp']
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/2021_10_29_추천시스템/data/u.data', sep = '\t', names = columns)

In [ ]:
from PIL import Image

In [8]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.decomposition import TruncatedSVD
from IPython.display import display, Image

#두 번째 데이터 셋

In [17]:
#display(Image(filename = '/content/drive/MyDrive/Colab Notebooks/2021_10_29_추천시스템/data/u_data.png'))

In [61]:
# 장르 분야
columns = ['item_id', 'movie title', 'release date', 'video release date', 'IMDb URL', 
           'unknown', 'Action', 'Adventure', 'Animation', 'Childrens', 
           'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 
           'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 
           'Sci-Fi', 'Thriller', 'War', 'Western']

In [21]:
movies = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/2021_10_29_추천시스템/data/u.item", sep="|",
                     names=columns, encoding='latin-1')

movie_names =movies[['item_id', 'movie title']]
c_movies_data = pd.merge(df, movie_names, on = 'item_id')
print(c_movies_data.shape)
c_movies_data.head()


#print(movies.shape)

#movies.head()

(100000, 5)


user_id  item_id  rating  timestamp   movie title
0      196      242       3  881250949  Kolya (1996)
1       63      242       3  875747190  Kolya (1996)
2      226      242       5  883888671  Kolya (1996)
3      154      242       3  879138235  Kolya (1996)
4      306      242       5  876503793  Kolya (1996)

# 미션:하나의 영화를 선택하고 관련 유사한 영화 10편을 추천해 주는 시스템을 만들어라

In [22]:
 rating_c = c_movies_data.pivot_table(values = 'rating', index = 'user_id', columns = 'movie title',
                                      fill_value = 0)
 
 rating_c

movie title  'Til There Was You (1997)  ...  Á köldum klaka (Cold Fever) (1994)
user_id                                 ...                                    
1                                    0  ...                                   0
2                                    0  ...                                   0
3                                    0  ...                                   0
4                                    0  ...                                   0
5                                    0  ...                                   0
...                                ...  ...                                 ...
939                                  0  ...                                   0
940                                  0  ...                                   0
941                                  0  ...                                   0
942                                  0  ...                                   0
943                                  0  ...                                   0

[943 rows x 1664 columns]

In [23]:
X = rating_c.T
print(X.shape)

(1664, 943)


# 차원축소

In [25]:
from sklearn.decomposition import TruncatedSVD

In [27]:
SVD = TruncatedSVD(n_components = 12, random_state = 5)
r_matrix = SVD.fit_transform(X) #10만 개의 리뷰  943명 - 1664명의 영화아이템을 (166 x 943) --> 1664 x 12
r_matrix.shape

(1664, 12)

In [28]:
corr_mat = np.corrcoef(r_matrix)
print(corr_mat.shape)
corr_mat

(1664, 1664)


array([[ 1.        , -0.11677136,  0.50912612, ...,  0.38185536,
         0.1925393 ,  0.49767897],
       [-0.11677136,  1.        ,  0.05531997, ...,  0.16334854,
         0.52127277,  0.28134103],
       [ 0.50912612,  0.05531997,  1.        , ...,  0.76371825,
         0.43466401,  0.19050485],
       ...,
       [ 0.38185536,  0.16334854,  0.76371825, ...,  1.        ,
         0.18096315,  0.12145833],
       [ 0.1925393 ,  0.52127277,  0.43466401, ...,  0.18096315,
         1.        ,  0.20183785],
       [ 0.49767897,  0.28134103,  0.19050485, ...,  0.12145833,
         0.20183785,  1.        ]])

In [39]:
rating_c.columns

Index([''Til There Was You (1997)', '1-900 (1994)', '101 Dalmatians (1996)',
       '12 Angry Men (1957)', '187 (1997)', '2 Days in the Valley (1996)',
       '20,000 Leagues Under the Sea (1954)', '2001: A Space Odyssey (1968)',
       '3 Ninjas: High Noon At Mega Mountain (1998)', '39 Steps, The (1935)',
       ...
       'Yankee Zulu (1994)', 'Year of the Horse (1997)', 'You So Crazy (1994)',
       'Young Frankenstein (1974)', 'Young Guns (1988)',
       'Young Guns II (1990)', 'Young Poisoner's Handbook, The (1995)',
       'Zeus and Roxanne (1997)', 'unknown',
       'Á köldum klaka (Cold Fever) (1994)'],
      dtype='object', name='movie title', length=1664)

# 유사 영화 찾기
 - star wars(1997)을 좋아합니다

In [43]:
col_idx = rating_c.columns.get_loc("101 Dalmatians (1996)")

In [44]:
corr_specific = corr_mat[col_idx]


In [46]:
result = pd.DataFrame({'corr_specific':corr_specific, "Movies": rating_c.columns})
print(result.shape)
result.head()

(1664, 2)


corr_specific                     Movies
0       0.509126  'Til There Was You (1997)
1       0.055320               1-900 (1994)
2       1.000000      101 Dalmatians (1996)
3       0.373695        12 Angry Men (1957)
4       0.275763                 187 (1997)

In [54]:
result.sort_values('corr_specific', ascending = False).head(80)

corr_specific                                           Movies
2          1.000000                            101 Dalmatians (1996)
693        0.944401  Homeward Bound II: Lost in San Francisco (1996)
713        0.931816              Hunchback of Notre Dame, The (1996)
659        0.922813                           Harriet the Spy (1996)
46         0.911541                   All Dogs Go to Heaven 2 (1996)
...             ...                                              ...
1123       0.786903                          Parent Trap, The (1961)
624        0.786078                            Goofy Movie, A (1995)
971        0.784086                                   Michael (1996)
1467       0.784044                        That Thing You Do! (1996)
1445       0.782929                   Sword in the Stone, The (1963)

[80 rows x 2 columns]

In [58]:
from sklearn.metrics.pairwise import cosine_similarity

In [59]:
cosine_mat = np.corrcoef(r_matrix)
print(cosine_mat.shape)
cosine_mat

(1664, 1664)


array([[ 1.        , -0.11677136,  0.50912612, ...,  0.38185536,
         0.1925393 ,  0.49767897],
       [-0.11677136,  1.        ,  0.05531997, ...,  0.16334854,
         0.52127277,  0.28134103],
       [ 0.50912612,  0.05531997,  1.        , ...,  0.76371825,
         0.43466401,  0.19050485],
       ...,
       [ 0.38185536,  0.16334854,  0.76371825, ...,  1.        ,
         0.18096315,  0.12145833],
       [ 0.1925393 ,  0.52127277,  0.43466401, ...,  0.18096315,
         1.        ,  0.20183785],
       [ 0.49767897,  0.28134103,  0.19050485, ...,  0.12145833,
         0.20183785,  1.        ]])

In [60]:
col_idx = rating_c.columns.get_loc("101 Dalmatians (1996)")
cosine_spec = cosine_mat[col_idx]
result = pd.DataFrame({'cosine_spec':cosine_spec, "Movies": rating_c.columns})
result.sort_values('cosine_spec', ascending = False).head(15)

cosine_spec                                           Movies
2        1.000000                            101 Dalmatians (1996)
693      0.944401  Homeward Bound II: Lost in San Francisco (1996)
713      0.931816              Hunchback of Notre Dame, The (1996)
659      0.922813                           Harriet the Spy (1996)
46       0.911541                   All Dogs Go to Heaven 2 (1996)
805      0.902762                                    Kazaam (1996)
435      0.899906                               Dragonheart (1996)
23       0.898412              Adventures of Pinocchio, The (1996)
764      0.892500                                      Jack (1996)
505      0.884585               Father of the Bride Part II (1995)
1547     0.877538                                   Twister (1996)
953      0.875717                                   Matilda (1996)
532      0.866382                                   Flipper (1996)
644      0.866275                          Grumpier Old Men (1995)
525      0.865257                                 First Kid (1996)